package session

const (
	WAITING_FOR_GUEST            = "WAITING_FOR_GUEST"
	WAITING_TO_START             = "WAITING_TO_START"
	WAITING_FOR_PLACEMENTS       = "WAITING_FOR_PLACEMENTSs"
	WAITING_FOR_OWNER_PLACEMENTS = "WAITING_FOR_OWNER_PLACEMENTS"
	WAITING_FOR_GUEST_PLACEMENTS = "WAITING_FOR_GUEST_PLACEMENTS"
	IN_GAME                      = "IN_GAME"
	FINISHED_GUEST_WON           = "FINISHED_GUEST_WON"
	FINISHED_OWNER_WON           = "FINISHED_OWNER_WON"
)
