apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret}}
      containers:
      - name: {{ .Values.name}}
        image: {{ .Values.image.name}}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.http.exposedPort}}
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 20
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.http.exposedPort}}
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 20
          periodSeconds: 30
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "1"
        env:
        - name: "APP_NAME"
          value: {{ .Values.name}}
        - name: "HTTP_PORT"
          value: "{{ .Values.http.exposedPort}}"
        - name: "WS_PORT"
          value: "{{ .Values.webSockets.exposedPort}}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: {{ .Values.name}}-s
          containerPort: {{ .Values.webSockets.exposedPort}}
        - name: {{ .Values.name}}-h
          containerPort: {{ .Values.http.exposedPort}}
          
---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
spec:
  minAvailable: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.name}}

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name}}
  ports:
  - protocol: TCP
    name: {{ .Values.name}}-s
    port: {{ .Values.webSockets.exposedPort}}
    targetPort: {{ .Values.webSockets.exposedPort}}
  - protocol: TCP
    name: {{ .Values.name}}-h
    port: {{ .Values.http.exposedPort}}
    targetPort: {{ .Values.http.exposedPort}}
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.webSockets.host}}`)
    kind: Rule
    services:
    - name: {{ .Values.name}}
      port: {{ .Values.webSockets.exposedPort}}
  tls:
    secretName: {{ .Values.ingress.tls.SecretName}}