### Ping
GET http://127.0.0.1:8080/ping

### ReadStore
GET http://127.0.0.1:8080/read

### CreatePlayer
POST http://127.0.0.1:8080/produce
Content-Type: application/json

{
    "type": "CreatePlayer",
    "payload":{
        "name": "pepe"
    }
}

### CreateSession
POST http://127.0.0.1:8080/produce
Content-Type: application/json

{
    "type": "CreateSession",
    "payload":{
        "owner_id": "mjmdDjLaCYebQhljZYOzlUyNmDyOwvPYbpqQfLrcxEPwwFjfSd"
    }
}

### DeleteSession
POST http://127.0.0.1:8080/produce
Content-Type: application/json

{
    "type": "DeleteSession",
    "payload":{
        "owner_id": "mjmdDjLaCYebQhljZYOzlUyNmDyOwvPYbpqQfLrcxEPwwFjfSd",
        "session_id": "MWXN"
    }
}